(in-package #:termis.compiler)

(defun cli-fail (control &rest arguments)
  (error 'compiler-driver-error :message (apply #'format nil control arguments)))

(defun parse-artifact-kind (value)
  (cond ((string= value "object") :object)
        ((string= value "executable") :executable)
        ((string= value "static-library") :static-library)
        ((string= value "shared-library") :shared-library)
        (t (cli-fail "unknown artifact kind ~A" value))))

(defun main (&optional (arguments (uiop:command-line-arguments)))
  "Command line entry point for `termis compile SOURCE`."
  (handler-case
      (let ((command (pop arguments)))
        (unless (and command (string= command "compile"))
          (cli-fail "usage: termis compile SOURCE [-o OUTPUT] [--emit KIND]"))
        (let ((source (pop arguments)) (output nil) (kind :executable)
              (triple nil) (cpu "generic") (features "") (libraries '())
              (paths '()) (frameworks '()))
          (unless source (cli-fail "compile requires a root Termis source file"))
          (loop while arguments
                for option = (pop arguments)
                do (cond ((or (string= option "-o") (string= option "--output"))
                          (setf output (or (pop arguments) (cli-fail "~A requires a path" option))))
                         ((string= option "--emit")
                          (setf kind (parse-artifact-kind
                                      (or (pop arguments) (cli-fail "--emit requires a kind")))))
                         ((string= option "--target")
                          (setf triple (or (pop arguments) (cli-fail "--target requires a triple"))))
                         ((string= option "--cpu")
                          (setf cpu (or (pop arguments) (cli-fail "--cpu requires a value"))))
                         ((string= option "--features")
                          (setf features (or (pop arguments) (cli-fail "--features requires a value"))))
                         ((or (string= option "-l") (string= option "--library"))
                          (push (or (pop arguments) (cli-fail "~A requires a library" option)) libraries))
                         ((or (string= option "-L") (string= option "--library-path"))
                          (push (or (pop arguments) (cli-fail "~A requires a path" option)) paths))
                         ((string= option "--framework")
                          (push (or (pop arguments) (cli-fail "--framework requires a name")) frameworks))
                         (t (cli-fail "unknown option ~A" option))))
          (let* ((target (resolve-compilation-target :triple triple :cpu cpu :features features))
                 (driver (make-compiler-driver :target target))
                 (artifact (compile-root driver source :artifact-kind kind :output output
                                          :link-options (make-link-options :libraries (nreverse libraries)
                                                                           :library-search-paths (nreverse paths)
                                                                           :frameworks (nreverse frameworks)))))
            (format t "~A~%" (artifact-path artifact))
            artifact)))
    (error (condition)
      (format *error-output* "termis: ~A~%" condition)
      (uiop:quit 1))))
