(in-package #:termis.backend.llvm)

(defun emit-place (backend expression)
  "Emit an LLVM address for a semantic Place expression."
  (cond
    ((typep expression 'termis:reference-expression)
     (let ((binding (termis:semantic-reference-binding expression)))
       (unless (or (typep binding 'termis:parameter-binding)
                   (typep binding 'termis:variable-declaration))
         (backend-fail "semantic binding ~S is not an LLVM place" binding))
       (backend-binding backend binding)))
    ((typep expression 'termis:dereference-expression)
     (emit-value backend (termis:dereference-expression-operand expression)))
    (t (backend-fail "expression ~S is not an LLVM place" expression))))

(defun emit-reference-value (backend expression)
  (let ((binding (termis:semantic-reference-binding expression)))
    (cond ((typep binding 'termis:function-declaration)
           (backend-binding backend binding))
          ((typep binding 'termis:constant-declaration)
           (llvm:build-load (llvm-backend-builder backend)
                            (backend-binding backend binding) "constant"
                            (lower-type backend (termis:expression-type expression))))
          ;; A reference remaining in a value position is a frontend
          ;; invariant violation: Step 10 inserts LOAD explicitly.
          (t (backend-fail "unlowered value reference to ~S" binding)))))

(defun emit-value (backend expression)
  "Emit EXPRESSION's already-resolved LLVM value."
  (cond
    ((typep expression 'termis:unit-expression)
     (llvm:const-int (lower-type backend (termis:expression-type expression)) 0))
    ((typep expression 'termis:boolean-literal)
     (llvm:const-int (lower-type backend (termis:expression-type expression))
                     (if (termis:boolean-literal-value expression) 1 0)))
    ((typep expression 'termis:integer-literal)
     (llvm:const-int (lower-type backend (termis:expression-type expression))
                     (termis:integer-literal-value expression)))
    ((typep expression 'termis:float-literal)
     (llvm:const-real (lower-type backend (termis:expression-type expression))
                      (termis:float-literal-value expression)))
    ((typep expression 'termis:reference-expression)
     (emit-reference-value backend expression))
    ((typep expression 'termis:load-expression)
     (llvm:build-load (llvm-backend-builder backend)
                      (emit-place backend (termis:load-expression-place expression))
                      "load"
                      (lower-type backend (termis:expression-type expression))))
    ((typep expression 'termis:address-expression)
     (emit-place backend (termis:address-expression-operand expression)))
    ((typep expression 'termis:dereference-expression)
     (emit-place backend expression))
    ((typep expression 'termis:store-expression)
     (llvm:build-store (llvm-backend-builder backend)
                       (emit-value backend (termis:assignment-expression-value expression))
                       (emit-place backend (termis:assignment-expression-target expression)))
     (llvm:const-int (lower-type backend (termis:expression-type expression)) 0))
    ((typep expression 'termis:sequence-expression)
     (let ((expressions (termis:sequence-expression-expressions expression)))
       (if expressions
           (loop for child in expressions
                 for value = (emit-value backend child)
                 finally (return value))
           (llvm:const-int (lower-type backend (termis:expression-type expression)) 0))))
    ((typep expression 'termis:primitive-call)
     (emit-primitive backend expression))
    ((typep expression 'termis:semantic-call)
     (let ((callee (termis:semantic-call-callee expression)))
       (unless (and (typep callee 'termis:reference-expression)
                    (typep (termis:semantic-reference-binding callee)
                           'termis:function-declaration))
         (backend-fail "ordinary call has no resolved function declaration"))
       (llvm:build-call
        (llvm-backend-builder backend)
        (backend-binding backend (termis:semantic-reference-binding callee))
        (mapcar (lambda (argument) (emit-value backend argument))
                (termis:semantic-call-arguments expression))
        "call")))
    (t (backend-fail "expression ~S has no LLVM value lowering" expression))))
