(defpackage #:termis.backend.llvm
  (:use #:cl)
  (:export
   #:llvm-backend
   #:llvm-backend-context
   #:llvm-backend-module
   #:llvm-backend-builder
   #:llvm-backend-target-triple
   #:llvm-backend-data-layout
   #:llvm-backend-pointer-width
   #:llvm-backend-target-machine
   #:llvm-backend-target-configuration
   #:make-llvm-backend
   #:target-configuration
   #:make-target-configuration
   #:target-configuration-triple
   #:target-configuration-cpu
   #:target-configuration-features
   #:target-configuration-relocation-model
   #:target-configuration-code-model
   #:codegen-configuration
   #:make-codegen-configuration
   #:codegen-configuration-target
   #:codegen-configuration-optimization-level
   #:codegen-configuration-relocation-model
   #:codegen-configuration-code-model
   #:codegen-configuration-output-kind
   #:linker-configuration
   #:make-linker-configuration
   #:linker-configuration-executable
   #:linker-configuration-arguments
   #:linker-configuration-libraries
   #:linker-configuration-library-paths
   #:linker-configuration-framework-paths
   #:emit-object
   #:emit-output
   #:build-executable
   #:validate-executable-entry-point
   #:lower-type
   #:emit-value
   #:emit-place
   #:generate-llvm
   #:verify-llvm-module
   #:print-llvm-module
   #:llvm-backend-error
   #:target-configuration-error
   #:object-emission-error
   #:object-emission-error-path
   #:entry-point-error
   #:linker-error
   #:linker-error-command
   #:linker-error-exit-status
   #:linker-error-stdout
   #:linker-error-stderr))

(in-package #:termis.backend.llvm)
