(defpackage #:termis
  (:use #:cl)
  (:shadow #:compile-file #:declaration)
  (:export
   #:compiler
   #:make-compiler
   #:source
   #:make-source
   #:source-from-file
   #:source-name
   #:source-contents
   #:source-location
   #:source-location-offset
   #:source-location-line
   #:source-location-column
   #:syntax
   #:make-syntax
   #:syntax-datum
   #:syntax-source
   #:syntax-start
   #:syntax-end
   #:syntax-with-datum
   #:termis-name
   #:make-termis-name
   #:termis-name-p
   #:termis-name-value
   #:termis-name=
   #:termis-symbol
   #:termis-symbol-name
   #:unit-literal
   #:unit-literal-p
   #:termis-list
   #:make-termis-list
   #:termis-list-p
   #:termis-list-elements
   #:termis-callable
   #:termis-callable-p
   #:termis-function
   #:make-termis-function
   #:termis-function-p
   #:termis-macro
   #:make-termis-macro
   #:termis-macro-p
   #:environment
   #:make-environment
   #:environment-parent
   #:environment-bind
   #:environment-lookup
   #:environment-child
   #:unbound-name-error
   #:unbound-name-error-name
   #:not-callable-error
   #:not-callable-error-value
   #:evaluate
   #:expand
   #:make-bootstrap-environment
   #:read-source
   #:compilation-unit
   #:compilation-unit-source
   #:compilation-unit-forms
   #:compilation-unit-declarations
   #:compilation-unit-namespace
   #:compilation-unit-environment
   #:compilation-unit-compile-time-environment
   #:module
   #:module-source
   #:module-forms
   #:module-declarations
   #:module-namespace
   #:module-environment
   #:module-lookup
   #:unit-declarations
   #:find-declaration
   #:register-declaration
   #:declaration
   #:declaration-name
   #:declaration-source
   #:declaration-expanded-syntax
   #:declaration-module
   #:declaration-compilation-unit
   #:type-declaration
   #:type-declaration-body
   #:function-declaration
   #:function-declaration-parameters
   #:function-declaration-return-type
   #:function-declaration-body
   #:macro-declaration
   #:macro-declaration-parameters
   #:macro-declaration-body
   #:constant-declaration
   #:constant-declaration-type
   #:constant-declaration-value
   #:variable-declaration
   #:variable-declaration-type
   #:variable-declaration-initializer
   #:definition-form-p
   #:process-definition
   #:expand-top-level
   #:top-level-expansion-result
   #:make-top-level-expansion-result
   #:top-level-expansion-result-definitions
   #:definition-error
   #:definition-error-syntax
   #:duplicate-declaration-error
   #:duplicate-declaration-error-name
   #:duplicate-declaration-error-existing
   #:non-definition-top-level-error
   #:compile-string
   #:compile-file
   #:source-error
   #:termis-read-error
   #:termis-read-error-source
   #:termis-read-error-location))
