(defpackage #:termis
  (:use #:cl)
  (:shadow #:compile-file #:declaration)
  (:export
   #:compiler
   #:make-compiler
   #:source
   #:make-source
   #:source-from-file
   #:source-name
   #:source-contents
   #:source-location
   #:source-location-offset
   #:source-location-line
   #:source-location-column
   #:syntax
   #:make-syntax
   #:syntax-datum
   #:syntax-source
   #:syntax-start
   #:syntax-end
   #:syntax-with-datum
   #:termis-name
   #:make-termis-name
   #:termis-name-p
   #:termis-name-value
   #:termis-name=
   #:termis-symbol
   #:termis-symbol-name
   #:unit-literal
   #:unit-literal-p
   #:termis-boolean-literal
   #:termis-boolean-literal-p
   #:termis-boolean-literal-value
   #:termis-list
   #:make-termis-list
   #:termis-list-p
   #:termis-list-elements
   #:termis-callable
   #:termis-callable-p
   #:termis-function
   #:make-termis-function
   #:termis-function-p
   #:termis-macro
   #:make-termis-macro
   #:termis-macro-p
   #:environment
   #:make-environment
   #:environment-parent
   #:environment-bind
   #:environment-lookup
   #:environment-child
   #:unbound-name-error
   #:unbound-name-error-name
   #:not-callable-error
   #:not-callable-error-value
   #:evaluate
   #:expand
   #:make-bootstrap-environment
   #:read-source
   #:compilation-unit
   #:compilation-unit-source
   #:compilation-unit-forms
   #:compilation-unit-declarations
   #:compilation-unit-namespace
   #:compilation-unit-environment
   #:compilation-unit-compile-time-environment
   #:compilation-unit-semantic-program
   #:module
   #:module-source
   #:module-forms
   #:module-declarations
   #:module-namespace
   #:module-environment
   #:module-lookup
   #:unit-declarations
   #:find-declaration
   #:register-declaration
   #:declaration
   #:semantic-binding
   #:semantic-binding-name
   #:declaration-name
   #:declaration-source
   #:declaration-expanded-syntax
   #:declaration-module
   #:declaration-compilation-unit
   #:type-declaration
   #:type-declaration-body
   #:function-declaration
   #:function-declaration-parameters
   #:function-declaration-return-type
   #:function-declaration-body
   #:macro-declaration
   #:macro-declaration-parameters
   #:macro-declaration-body
   #:constant-declaration
   #:constant-declaration-type
   #:constant-declaration-value
   #:variable-declaration
   #:variable-declaration-type
   #:variable-declaration-initializer
   #:semantic-scope
   #:make-semantic-scope
   #:semantic-scope-parent
   #:semantic-scope-bind
   #:semantic-scope-find
   #:semantic-scope-lookup
   #:semantic-scope-child
   #:semantic-scope-owning-program
   #:semantic-scope-owning-type-context
   #:semantic-scope-function
   #:semantic-scope-owning-function
   #:semantic-program
   #:semantic-program-bootstrap-scope
   #:semantic-program-module-scope
   #:semantic-program-declarations
   #:semantic-program-declaration
   #:semantic-program-type-context
   #:make-bootstrap-semantic-scope
   #:parameter-binding
   #:parameter-binding-syntax
   #:parameter-binding-type-syntax
   #:parameter-binding-type-reference
   #:parameter-binding-type
   #:pattern-binding
   #:pattern-binding-syntax
   #:pattern-binding-type
   #:let-binding
   #:let-binding-syntax
   #:let-binding-source
   #:let-binding-type-syntax
   #:let-binding-type-reference
   #:let-binding-type
   #:let-binding-initializer
   #:semantic-declaration
   #:semantic-declaration-source-declaration
   #:semantic-type-declaration
   #:semantic-type-declaration-type
   #:semantic-constant-declaration
   #:semantic-constant-declaration-type-reference
   #:semantic-constant-declaration-type
   #:semantic-constant-declaration-initializer
   #:semantic-variable-declaration
   #:semantic-variable-declaration-type-reference
   #:semantic-variable-declaration-type
   #:semantic-variable-declaration-initializer
   #:semantic-function-declaration
   #:semantic-function-declaration-scope
   #:semantic-function-declaration-parameters
   #:semantic-function-declaration-return-type-reference
   #:semantic-function-declaration-return-type
   #:semantic-function-declaration-type
   #:semantic-function-declaration-body
   #:semantic-expression
   #:semantic-expression-syntax
   #:semantic-expression-type
   #:expression
   #:expression-syntax
   #:expression-source
   #:expression-type
   #:semantic-literal
   #:unit-expression

   #:unit-expression-value
   #:unit-value
   #:boolean-literal
   #:boolean-literal-value
   #:integer-literal
   #:integer-literal-value
   #:float-literal
   #:float-literal-value
   #:string-literal
   #:string-literal-value
   #:semantic-reference
   #:semantic-reference-name
   #:semantic-reference-binding
   #:reference-expression
   #:semantic-call
   #:semantic-call-callee
   #:semantic-call-arguments
   #:call-expression
   #:primitive-call
   #:primitive-call-operation
   #:conversion-expression
   #:sequence-expression
   #:sequence-expression-expressions
   #:let-expression
   #:let-expression-bindings
   #:let-expression-scope
   #:let-expression-body
   #:address-expression
   #:address-expression-operand
   #:dereference-expression
   #:dereference-expression-operand
   #:load-expression
   #:load-expression-place
   #:assignment-expression
   #:assignment-expression-target
   #:assignment-expression-value
   #:store-expression
   #:return-expression
   #:return-expression-value
   #:pattern
   #:pattern-syntax
   #:pattern-type
   #:literal-pattern
   #:literal-pattern-value
   #:boolean-pattern
   #:integer-pattern
   #:wildcard-pattern
   #:binding-pattern
   #:binding-pattern-binding
   #:match-case
   #:match-case-syntax
   #:match-case-pattern
   #:match-case-scope
   #:match-case-expression
   #:match-expression
   #:match-expression-value
   #:match-expression-cases
   #:place-expression
   #:place-expression-addressable-p
   #:place-expression-writable-p
   #:semantic-type-syntax
   #:semantic-unit-type-syntax
   #:semantic-pointer-type-syntax
   #:semantic-pointer-type-syntax-target
   #:termis-type
   #:unit-type
   #:never-type
   #:boolean-type
   #:string-type
   #:integer-type
   #:integer-type-signed
   #:integer-type-width
   #:float-type
   #:float-type-width
   #:pointer-type
   #:pointer-type-target
   #:pointer-type-pointee
   #:function-type
   #:function-type-parameters
   #:function-type-result
   #:defined-type
   #:defined-type-declaration
   #:type-context
   #:make-type-context
   #:type-context-unit-type
   #:type-context-never-type
   #:type-context-unit-value
   #:type-context-pointer-width
   #:type-context-unit-representation-type
   #:unit-machine-representation
   #:type-context-boolean-type
   #:type-context-string-type
   #:type-context-integer-type
   #:type-context-float-type
   #:type-context-pointer-type
   #:type-context-function-type
   #:type-context-defined-type
   #:builtin-type-binding
   #:builtin-type-binding-type
   #:builtin-type-declaration
   #:builtin-intrinsic-binding
   #:builtin-intrinsic-binding-type
   #:primitive-binding
   #:primitive-binding-operation
   #:primitive-operation
   #:primitive-operation-identity
   #:primitive-operation-name
   #:primitive-operation-parameter-types
   #:primitive-operation-result-type
   #:primitive-operation-kind
   #:primitive-operation-nan-semantics
   #:expected-type-error
   #:expected-type-error-binding
   #:resolve-type
   #:resolve-types
   #:infer-expression
   #:check-expression
   #:same-type-p
   #:compatible-p
   #:type-mismatch-error
   #:type-mismatch-error-actual
   #:type-mismatch-error-expected
   #:semantic-not-callable-error
   #:wrong-argument-count-error
   #:wrong-argument-count-error-expected
   #:wrong-argument-count-error-actual
   #:not-addressable-error
   #:not-writable-error
   #:invalid-expression-error
   #:non-exhaustive-match-error
   #:non-exhaustive-match-error-uncovered
   #:unreachable-pattern-error
   #:unreachable-pattern-error-covering-pattern
   #:unreachable-expression-error
   #:return-outside-function-error
   #:backend-validation-error
   #:validate-for-backend
   #:backend-representable-type-p
   #:build-semantic-expression
   #:resolve-compilation-unit
   #:definition-form-p
   #:process-definition
   #:expand-top-level
   #:top-level-expansion-result
   #:make-top-level-expansion-result
   #:top-level-expansion-result-definitions
   #:definition-error
   #:definition-error-syntax
   #:duplicate-declaration-error
   #:duplicate-declaration-error-name
   #:duplicate-declaration-error-existing
   #:non-definition-top-level-error
   #:semantic-error
   #:semantic-error-syntax
   #:unresolved-name-error
   #:unresolved-name-error-name
   #:duplicate-local-binding-error
   #:invalid-definition-context-error
   #:compile-string
   #:compile-file
   #:source-error
   #:termis-read-error
   #:termis-read-error-source
   #:termis-read-error-location))
